### ISSUE TITLE
Make reference to devtools

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/doc#1]
I do not use the command line interface to check and build packages and instead use a combination of:

```r 
devtools::document()
devtools::check()
devtools::install()
devtools::load_all()
```
from the devtools package. Hadley and co. have written a lot of useful stuff on building and checking packages here
http://r-pkgs.had.co.nz/

which I find really useful, and would be a good resource to point people towards I think.

**Comment by arni-magnusson** [comment]
da4c7821731c14ab169b251e0d24cd46ff1e7ccf
