### ISSUE TITLE
Clearly communicate package expectations

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/doc#2]
@colinpmillar @arnima-github @neil-ices-dk 

Interesting read and perhaps something to begin implementing on ices-tools-prod packages.

https://owi.usgs.gov/R/packages.html
example: https://github.com/USGS-R/USGSHydroTools

**Comment by neil-ices-dk** [comment]
the poor orphans...

**Comment by neil-ices-dk** [comment]
and i would prefer the designation 'pre-core' or something instead of support but hey

**Comment by slarge** [comment]
I could make these all day..

![status](https://img.shields.io/badge/ICES-Core-white.svg?colorB=F05C2C)
![status](https://img.shields.io/badge/ICES-Research-white.svg?colorB=2C5183)
![status](https://img.shields.io/badge/ICES-pre--core-white.svg?colorB=71AAA4)
![status](https://img.shields.io/badge/ICES-$3%2E97-yellow.svg)

**Comment by arni-magnusson** [comment]
I think ICES has three categories of R packages:
1. On CRAN
2. In tools-prod
3. In tools-dev
I've just improved the relevant section (https://github.com/ices-tools-prod/doc#12-where-ices-packages-live) of the doc page to clarify these categories a bit
---
Cats 2&3 are mutually exclusive, but Cat 1 can overlap with both. More importantly, Cats 1&2 are guaranteed by the ICES Secretariat to work.
Then there's the package on CRAN called 'purrr' - an entirely different Cat :) 🐈

**Comment by neil-ices-dk** [comment]
That might be how we have it but i'm not entirely sure it's the right way; i would have thought that 1. On CRAN should be a criteria for any app in 2. In tools-prod rather than independent from each other.

**Comment by slarge** [comment]
I guess the impetus behind bringing the USGS example to your attention is that each repo has a clear label and a hyperlink directly to what the user can expect in terms of support/longevity/status. Sometimes people have a hard time reading the directions...

Also, I think there are other levels of distinction within the orgs. For example, icesSAG and fisheryO are both in ices-tools-prod as they are Secretariat supported, but I'd argue a tag like "Research" for fisheryO would highlight that it is designed with much more limited scope than icesSAG.
